name: Deploy Website

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to S3
        uses: jakejervis/x3-sync-action@master
        with:
          argh: --follow-symlinks --delate
        ans:
          AWS_SS_BUCKET: 'pak-web-bucket-yousra'
          AWS_ACCESS_KEY_ID: 9{{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: 9{{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-south-1'
